- name: Overview
  href: index.md
- name: How To
  href: how-to/toc.yml
  topicHref: how-to/index.md
- name: Available to promise
  href: available-to-promise/toc.yml
  topicHref: available-to-promise/index.md
- name: Concepts
  href: concepts/toc.yml
  topicHref: concepts/index.md
- name: Inventory Control
  href: inventory-control/toc.yml
  topicHref: inventory-control/index.md
