name: Generate/Update DocFX TOC

on:
  workflow_dispatch:
    inputs:
      target_path:
        description: "Папката, за която да се генерира TOC (пример: docs/operators)"
        required: true
        default: "docs"
      auto_create_subdirs:
        description: "Създай празни index.md и toc.yml в поддиректориите (1 ниво)"
        required: true
        type: boolean
        default: true
      update_parent:
        description: "Ъпдейтни родителския toc.yml с новата секция"
        required: true
        type: boolean
        default: true
      include_root_files:
        description: "Включи и други .md файлове в текущата папка (освен index/readme)"
        required: true
        type: boolean
        default: false
      require_sub_index:
        description: "Включвай поддиректория в TOC само ако има index.md/readme.md"
        required: true
        type: boolean
        default: false
      require_sub_toc:
        description: "Включвай поддиректория в TOC само ако има собствен toc.yml"
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  gen-toc:
    name: Generate TOC for "${{ inputs.target_path }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      # 👉 ако скриптът ти е в друга папка, смени пътя тук
      - name: Run gen_docfx_root_toc_v4.py
        env:
          TARGET_PATH: ${{ inputs.target_path }}
        run: |
          set -e
          PY_SCRIPT="gen_docfx_root_toc_v4.py"
          if [ ! -f "$PY_SCRIPT" ]; then
            echo "::error file=$PY_SCRIPT::Не е намерен $PY_SCRIPT в корена на репото."
            exit 1
          fi

          ARGS="--root \"$TARGET_PATH\" --write"
          ${{ inputs.auto_create_subdirs && 'ARGS="$ARGS --auto-create-subdirs"' || 'true' }}
          ${{ inputs.update_parent && 'ARGS="$ARGS --update-parent"' || 'true' }}
          ${{ inputs.include_root_files && 'ARGS="$ARGS --include-root-files"' || 'true' }}
          ${{ inputs.require_sub_index && 'ARGS="$ARGS --require-sub-index"' || 'true' }}
          ${{ inputs.require_sub_toc && 'ARGS="$ARGS --require-sub-toc"' || 'true' }}

          echo "Running: python $PY_SCRIPT $ARGS"
          eval python "$PY_SCRIPT" $ARGS

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "toc-bot"
            git config user.email "toc-bot@users.noreply.github.com"
            git add -A
            git commit -m "chore(docs): auto-generate toc.yml for ${{ inputs.target_path }}"
            git push
          else
            echo "No changes to commit."
          fi
