name: Update DocFX TOC

on:
  workflow_dispatch:
    inputs:
      target_path:
        description: "Папката, за която да се обнови TOC (пример: docs/operators)"
        required: true
        default: "docs"

permissions:
  contents: write

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run TOC generator and commit
        env:
          TARGET_PATH: ${{ inputs.target_path }}
        run: |
          PY_SCRIPT="gen_docfx_root_toc_v4.py"
          echo "🚀 Генерирам TOC за: $TARGET_PATH"
          python "$PY_SCRIPT" --root "$TARGET_PATH" --write --auto-create-subdirs --update-parent --require-sub-index --verbose

          if [ -n "$(git status --porcelain)" ]; then
            echo "📦 Променени файлове:"
            git status --short
            git config user.name "toc-bot"
            git config user.email "toc-bot@users.noreply.github.com"
            git add -A
            git commit -m "chore(docs): auto-generate toc.yml for ${{ inputs.target_path }}"
            git push
            echo "✅ Промените са записани."
          else
            echo "✅ Няма промени за commit."
          fi
